### ISSUE TITLE
Error on steampipe : wrong check in main.rs, line 324 : change portal_vpk_dir.vpk to portal_pak_dir.vpk

### ISSUE THREAD

**Issue by Skkeye** [wozniak/portal-tools#1]
File in /portal : 
![image](https://user-images.githubusercontent.com/38301149/145936709-3aab2251-d72c-48a2-848c-1f114f2cbdff.png)

File checked in main.rs : 
![image](https://user-images.githubusercontent.com/38301149/145936782-ff59743d-66f1-460a-aa82-ffe23d64a343.png)

**Comment by SparkyJoule** [comment]
I don't know if it is valid for all steampipe versions...
maybe add another check instead of changing the check to be certain...

**Comment by wozniak** [comment]
Yeah no I just didn't actually test Steampipe I'm going to be honest with you.

**Comment by Skkeye** [comment]
Its fine my guy

**Comment by wozniak** [comment]
fixed in #5
