### ISSUE TITLE
Wrong path specified in main.rs, lines 48 and 52

### ISSUE THREAD

**Issue by Skkeye** [wozniak/portal-tools#2]
Current paths :
![image](https://user-images.githubusercontent.com/38301149/145942367-78364291-3df5-4462-97b9-28f4f4025349.png)

Should be : 
{}/portal/custom/portal_tools/materials/models/weapons/v_models/v_portalgun
{}/portal/custom/portal_tools/materials/models/weapons/w_models/portalgun

Need to add a "weapons" folder before v and w models

**Comment by wozniak** [comment]
fixed in #5
